apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: setup-hosts
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: setup-hosts
  template:
    metadata:
      labels:
        name: setup-hosts
    spec:
      initContainers:
      - name: setup-hosts
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Start configuration /etc/hosts"
          grep -q myapp /tmp/etc/hosts || echo "172.18.0.50 myapp.localhost.com" >> /tmp/etc/hosts
        volumeMounts:
        - name: etc
          mountPath: /tmp/etc
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.6
      volumes:
      - name: etc
        hostPath:
          path: /etc
